twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        # point this wherever your css files live
        '%kernel.project_dir%/assets/styles': styles
    
    date:
        format: 'd.m.Y'
        interval_format: '%%d days'
        timezone: 'Europe/Berlin'
        
    globals:
        'app_title': '%app.title%'
    
    form_themes: [ 'bootstrap_5_layout.html.twig' ]

when@test:
    twig:
        strict_variables: true
